### ISSUE TITLE
Exclusion des graphiques de la détection du type de dataviz 

### ISSUE THREAD

**Issue by Clement-Bader-bzh** [spelhate/mreport#161]
Le type de dataviz (table, chart, figure, text, ...) est détecté automatiquement. 
Dans un certain nombre de cas, alors que le type "chart" est précisé dans la table "dataviz", la seule représentation proposée est "table" (et non "chart"). Cela correspond à des cas où, pour certaines entité, une seule modalité (ou aucune) n'existe (exemple : représentation des aides selon le type par territoire, mais où certains territoires ne reçoivent aucune aide). 

Cela empêche d'utiliser une représentation graphiques alors que celle-ci est souhaitée (et que l'affichage d'un graphique sans données est possible). 

![choix_graph](https://user-images.githubusercontent.com/77267495/158421444-eb964b38-ad8a-459f-9d83-0590fdcde089.PNG)

**Comment by lecault** [comment]
As tu d'autres exemple ? Dans celui que tu montres, ça semble logique au vue de comment la donnée est structuré qu'on ne puisse pas faire de chart.

**Comment by Clement-Bader-bzh** [comment]
Oui, effectivement, j'avais retravaillé la dataviz pour un tableau. La data viz qui ne fonctionnait pas est celle-ci (il n'est pas proposé de "chart", mais uniquement 'figure' ou 'text'. 
(Il n'est pas exclu que je me soit trompé dans la mise en forme des données, mais j'ai vérifié et cela me semblait ok).

Partie mise en forme
![image](https://user-images.githubusercontent.com/77267495/159224522-49cfa99a-5f48-4f09-9b9e-a60291080b9f.png)

Données correspondantes
![image](https://user-images.githubusercontent.com/77267495/159224574-fe4f1f02-c4fe-4dc4-b487-e8fc9c24a147.png)

**Comment by spelhate** [comment]
@Clement-Bader-bzh , @lecault : Pouvez-vous me fournir une extraction de table sql afin que je puisse reproduire le bug ?

**Comment by lecault** [comment]
Du coup c'est bon ?

**Comment by spelhate** [comment]
En principe oui. A tester.Le 21 avr. 2022 14:41, Loïc E ***@***.***> a écrit :
Du coup c'est bon ?
